sleep 2 finish

diff --git a/.github/workflows/flask.yml b/.github/workflows/flask.yml
--- a/.github/workflows/flask.yml
+++ b/.github/workflows/flask.yml
@@ -17,7 +17,7 @@ jobs:
         run: docker build -t flask-app .
 
       - name: Run Container
-        run: docker run -d -p 5000:5000 flask-app
+        run: docker run -d --network host flask-app
 
       - name: Wait for API (retry)
         run: |
@@ -36,6 +36,12 @@ jobs:
       - name: Test API
         run: |
           for i in {1..10}; do
-          curl http://127.0.0.1:5000 && break
+          if curl -s http://127.0.0.1:5000; then
+          echo "API is up!"
+          exit 0
+          fi
           sleep 2
           done
+
+          echo "API failed to start"
+          exit 1
